### ISSUE TITLE
not correct timezone in magnusbilling 6

### ISSUE THREAD

**Issue by PBX-Ramdas** [magnussolution/magnusbilling6#1]
Hello,

just starting to use magnusbilling and first thanks for this great project. I have follow these steps to install magnusbilling on Centos 7.

cd /usr/src/
yum -y install wget
wget https://raw.githubusercontent.com/magnussolution/magnusbilling6/master/script/install.sh
chmod +x install.sh
./install.sh

During the installation script, at some point, you have to specify the timezone you want to use. But I notice that although I have chosen my desired timezone, when the installing is finish and reboot, magnusbilling is still using the hardcoded timezone America/Sao_Paulo.

I had chosen for the timezone Europe/Amsterdam. The only way to let magnusbilling use the correct timezone, was to manaully edit the php configuration file.

So maybe some one can look into this issue with the script.

Best Regards
PBX-Ramdas

**Comment by magnussolution** [comment]
hi, please try the new MagnusBilling V7 

https://github.com/magnussolution/magnusbilling

Best regards
